### PR TITLE
Test escaping changes

### PR DESCRIPTION
**Pull request by abgruszecki**
Tests https://github.com/lampepfl/dotty/pull/9526.

### CODE REVIEW

**Comment by abgruszecki** [comment]
@liufengyun I don't know why AppVeyor test fails. It probably shouldn't do that, right?

**Comment by abgruszecki** [comment]
The log is just:
```
git clone -q --branch=test-escaping-changes https://github.com/lampepfl/packtest.git C:\projects\packtest-s6xq2
git checkout -qf 831bd3a896509726c52c1341c1d783a3b6f20b8c
$url = get-content artifacts | select-string "zip" | Foreach {($_ -split  '=', 2)[1]};  wget -O dotty.zip $url
Expand-Archive dotty.zip -DestinationPath .
New-Object : Exception calling ".ctor" with "3" argument(s): "End of Central Directory record could not be found."
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:934 char:23
+ ... ipArchive = New-Object -TypeName System.IO.Compression.ZipArchive -Ar ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
SET PATH=%bash%;%PATH%
bash windows
windows: line 2: cd: dotty-*: No such file or directory
Command exited with code 1
```

**Comment by abgruszecki** [comment]
And for clarity, I can run the following on my machine just fine:
```
wget -O dotty.zip https://www.dropbox.com/s/daz9nu6t7l0538b/dotty-0.27.0-bin-SNAPSHOT.zip
```

**Comment by liufengyun** [comment]
It seems related to how we `unzip` or `zip`, we are missing top-level directory.

```
cd dotty-*
```

**Comment by liufengyun** [comment]
We didn't run the test for a long time. It seems something is broken with windows test.

**Comment by abgruszecki** [comment]
So what do we do now? It seems the repo wasn't used for a few releases - last PR mentions Dotty 0.13.0. Do we just merge the Dotty PR?

**Comment by liufengyun** [comment]
The following two lines might be the cause of the problem:

https://github.com/lampepfl/packtest/blob/9639d820b7230ed69f069d3c5cc47a91e72f59be/.appveyor.yml#L14-L15

> Do we just merge the Dotty PR?

If we are optimistic that the PR will not break windows, then we can try to fix the windows CI later.

**Comment by abgruszecki** [comment]
If we take a look at the Dotty PR, then all it does is 1) remove useless/dangerous `eval`-s from Dotty repo scripts (which isn't really important) and 2) add single quotes around parameters which are passed to `eval` before actually being used (in `dotc` and similar scripts). I tested manually that we actually can now pass classnames with dollars to `bin/dotc`. However, we only need to worry about 2), and I'd be pretty confident that that change is safe.

**Comment by liufengyun** [comment]
Then let's have the PR in first.

**Comment by abgruszecki** [comment]
OK, then closing this PR and merging lampepfl/dotty#9526.

**Pull request closed without merging**
